version: '3.9'

services:
  bot:
    build:
      dockerfile: ./Dockerfile
    container_name: bot
    environment:
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN}
      - DB_DSN=${DB_DSN}
    env_file: .env
    restart: always
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_started
    network_mode: "host"

  db:
    image: postgres:latest
    container_name: psql
    restart: on-failure
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'